"use client";
import { motion } from "motion/react";
import { BookOpen, Check, Circle, Dumbbell, Flame, MoreHorizontal, Moon, Plus, Sparkles, Sunrise } from "lucide-react";
import { useDayOS } from "@/components/providers";
import { GlassCard } from "@/components/glass/glass";
import { Button } from "@/components/ui/button";

const habitIcons=[Sunrise,BookOpen,Dumbbell,Moon];
export function HabitsView(){const {habits,toggleHabit}=useDayOS();const complete=habits.filter((item)=>item.completedToday).length;return <main className="workspace habits-workspace"><header className="page-heading compact"><div><span className="overline">SMALL RHYTHMS</span><h1>Habits</h1><p>Consistency without pressure.</p></div><Button><Plus/> New habit</Button></header><GlassCard className="habit-progress"><div className="habit-ring" style={{"--progress":`${complete/habits.length*360}deg`} as React.CSSProperties}><span><b>{complete}</b>/{habits.length}</span></div><div><span className="overline">TODAY’S RHYTHM</span><h2>{complete===habits.length?"Everything is complete.":`${habits.length-complete} gentle nudges remain.`}</h2><p>Your habits support the day. They don’t define its worth.</p></div><div className="streak"><Flame/><div><b>8 days</b><small>steady rhythm</small></div></div></GlassCard><section className="habit-grid">{habits.map((habit,index)=>{const Icon=habitIcons[index%habitIcons.length]!;return <motion.article layout key={habit.id}><GlassCard className={habit.completedToday?"habit-card completed":"habit-card"}><header><div className="habit-icon"><Icon/></div><button><MoreHorizontal/></button></header><span className="overline">{habit.lifeArea}</span><h2>{habit.name}</h2><p>{habit.estimatedDurationMinutes} min · {habit.targetPerWeek===7?"every day":`${habit.targetPerWeek}× per week`}</p><div className="week-dots">{["M","T","W","T","F","S","S"].map((day,i)=><span className={i<Math.min(habit.streak,7)?"done":""} key={`${day}${i}`}>{day}</span>)}</div><button className="habit-complete" onClick={()=>void toggleHabit(habit.id)}>{habit.completedToday?<><Check/> Complete</>:<><Circle/> Mark complete</>}</button><footer><Flame/><b>{habit.streak}-day streak</b><span>{habit.frequencyType.replaceAll("_"," ").toLowerCase()}</span></footer></GlassCard></motion.article>})}<GlassCard className="habit-add"><button><Plus/><b>Add a new rhythm</b><span>Build consistency around something meaningful.</span></button></GlassCard></section><GlassCard className="habit-note"><Sparkles/><div><b>Five days, not perfection.</b><p>You read on 5 of the last 7 days. That’s a rhythm worth keeping.</p></div></GlassCard></main>}
