"use client";

import { Check, ChevronRight, Clock3, Coffee, Database, Droplets, Globe2, LockKeyhole, Moon, Palette, ShieldCheck, Sun, UserRound } from "lucide-react";
import type { UpdateProfileInput } from "@dayos/contracts";
import type { RoutineWindowPreference, UserProfile } from "@dayos/domain";
import { useTheme } from "next-themes";
import { useState, useSyncExternalStore } from "react";
import { useDayOS } from "@/components/providers";
import { GlassCard } from "@/components/glass/glass";
import { Button } from "@/components/ui/button";

const dayLabels = ["S", "M", "T", "W", "T", "F", "S"];
const styleCopy = { STRUCTURED: "Minimal open gaps", BALANCED: "Useful breathing room", SPACIOUS: "More recovery space" } as const;

export function SettingsView() {
  const { profile, updateProfile } = useDayOS();
  if (!profile) return <main className="workspace settings-workspace"><div className="page-loading">Loading your saved settings…</div></main>;
  return <SettingsForm key={profile.id} profile={profile} updateProfile={updateProfile} />;
}

function SettingsForm({ profile, updateProfile }: { profile: UserProfile; updateProfile(input: UpdateProfileInput): Promise<void> }) {
  const { theme, setTheme } = useTheme(); const mounted = useSyncExternalStore(() => () => {}, () => true, () => false);
  const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [form, setForm] = useState({
    displayName: profile.displayName, wakeTime: profile.wakeTime, sleepTime: profile.sleepTime, workStartTime: profile.workStartTime, workEndTime: profile.workEndTime,
    defaultFocusDurationMinutes: profile.defaultFocusDurationMinutes, defaultBreakDurationMinutes: profile.defaultBreakDurationMinutes, dailyWaterTargetMl: profile.dailyWaterTargetMl,
    routineWindows: profile.preferences.routineWindows, mealWindows: profile.preferences.mealWindows, freeTime: profile.preferences.freeTime, planningStyle: profile.preferences.planningStyle
  });
  const change = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((current) => ({ ...current, [key]: value }));
  const changeRoutine = (id: string, patch: Partial<RoutineWindowPreference>) => change("routineWindows", form.routineWindows.map((routine) => routine.id === id ? { ...routine, ...patch } : routine));
  const toggleDay = (routine: RoutineWindowPreference, day: number) => changeRoutine(routine.id, { days: routine.days.includes(day) ? routine.days.filter((item) => item !== day) : [...routine.days, day].sort() });
  const save = async () => { const work = form.routineWindows.find((routine) => routine.kind === "WORK" && routine.active); setSaving(true); setSaved(false); setError(null); try { await updateProfile({ ...form, ...(work ? { workStartTime: work.start, workEndTime: work.end } : {}) }); setSaved(true); window.setTimeout(() => setSaved(false), 2500); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your settings could not be saved."); } finally { setSaving(false); } };
  const changeMeal = (name: keyof typeof form.mealWindows, field: "start" | "end", value: string) => change("mealWindows", { ...form.mealWindows, [name]: { ...form.mealWindows[name], [field]: value } });
  return <main className="workspace settings-workspace"><header className="page-heading compact"><div><span className="overline">YOUR DAY, YOUR RULES</span><h1>Settings</h1><p>Edit the weekly rhythm DayOS uses to plan every hour.</p></div><Button disabled={saving} onClick={() => void save()}>{saved ? <><Check /> Saved</> : saving ? "Rebuilding week…" : "Save and rebuild"}</Button></header>{error && <p className="form-error" role="alert">{error}</p>}<div className="settings-layout"><nav className="settings-nav">{[{ n: "Profile", i: UserRound, id: "profile-settings" }, { n: "Weekly rhythm", i: Clock3, id: "rhythm-settings" }, { n: "Appearance", i: Palette, id: "appearance-settings" }, { n: "Privacy", i: ShieldCheck, id: "privacy-settings" }].map(({ n, i: Icon, id }, index) => <button className={index === 1 ? "active" : ""} onClick={() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" })} key={n}><Icon />{n}<ChevronRight /></button>)}</nav><div className="settings-content">
    <GlassCard className="settings-card" id="profile-settings"><header><span><UserRound /></span><div><h2>Profile</h2><p>The name shown across your personal space.</p></div></header><label className="profile-name-field"><span>Display name</span><input value={form.displayName} onChange={(event) => change("displayName", event.target.value)} aria-label="Display name" /></label></GlassCard>
    <GlassCard className="settings-card" id="rhythm-settings"><header><span><Clock3 /></span><div><h2>Day boundaries</h2><p>Nothing is scheduled outside waking hours or through protected sleep.</p></div></header><div className="settings-grid"><label><span><Sun />Wake time</span><input type="time" value={form.wakeTime} onChange={(event) => change("wakeTime", event.target.value)} /></label><label><span><Moon />Sleep time</span><input type="time" value={form.sleepTime} onChange={(event) => change("sleepTime", event.target.value)} /></label></div><div className="preference-row"><div><b>Focus block length</b><p>Default duration for deep-focus sessions.</p></div><select value={form.defaultFocusDurationMinutes} onChange={(event) => change("defaultFocusDurationMinutes", Number(event.target.value))}><option value="60">60 minutes</option><option value="90">90 minutes</option><option value="120">120 minutes</option></select></div><div className="preference-row"><div><b>Break after focus</b><p>Recovery after sustained concentration.</p></div><select value={form.defaultBreakDurationMinutes} onChange={(event) => change("defaultBreakDurationMinutes", Number(event.target.value))}><option value="10">10 minutes</option><option value="15">15 minutes</option><option value="20">20 minutes</option></select></div></GlassCard>
    <GlassCard className="settings-card"><header><span><Clock3 /></span><div><h2>Weekly time windows</h2><p>Tell DayOS what usually belongs in each part of your week.</p></div></header><div className="routine-editor settings-routines">{form.routineWindows.map((routine) => <div className={`routine-row ${routine.active ? "" : "inactive"}`} key={routine.id}><button className={`routine-toggle ${routine.active ? "on" : ""}`} onClick={() => changeRoutine(routine.id, { active: !routine.active })} aria-label={`${routine.active ? "Disable" : "Enable"} ${routine.title}`}><i /></button><div className="routine-main"><input value={routine.title} onChange={(event) => changeRoutine(routine.id, { title: event.target.value })} aria-label={`${routine.kind} title`} /><small>{routine.kind.toLowerCase().replaceAll("_", " ")}</small></div><div className="routine-times"><input type="time" value={routine.start} onChange={(event) => changeRoutine(routine.id, { start: event.target.value })} /><span>to</span><input type="time" value={routine.end} onChange={(event) => changeRoutine(routine.id, { end: event.target.value })} /></div><div className="routine-days">{dayLabels.map((label, day) => <button className={routine.days.includes(day) ? "active" : ""} onClick={() => toggleDay(routine, day)} aria-label={`${label} day ${day + 1}`} key={day}>{label}</button>)}</div></div>)}</div></GlassCard>
    <GlassCard className="settings-card"><header><span><Coffee /></span><div><h2>Meals and open time</h2><p>Essentials stay protected; abundance stays intentional.</p></div></header>{(["breakfast", "lunch", "dinner"] as const).map((name) => <div className="window-row meal-setting" key={name}><span className="window-icon"><Coffee /></span><div><b>{name.charAt(0).toUpperCase() + name.slice(1)}</b><small>Every day</small></div><input aria-label={`${name} starts`} type="time" value={form.mealWindows[name].start} onChange={(event) => changeMeal(name, "start", event.target.value)} /><span>to</span><input aria-label={`${name} ends`} type="time" value={form.mealWindows[name].end} onChange={(event) => changeMeal(name, "end", event.target.value)} /></div>)}<div className="planning-style settings-planning-style">{(["STRUCTURED", "BALANCED", "SPACIOUS"] as const).map((style) => <button className={form.planningStyle === style ? "active" : ""} onClick={() => change("planningStyle", style)} key={style}><b>{style.charAt(0) + style.slice(1).toLowerCase()}</b><small>{styleCopy[style]}</small></button>)}</div><label className="profile-name-field"><span>Suggest these uses for abundant time</span><input value={form.freeTime.preferredUses.join(", ")} onChange={(event) => change("freeTime", { ...form.freeTime, preferredUses: event.target.value.split(",").map((value) => value.trim()).filter(Boolean) })} /></label></GlassCard>
    <GlassCard className="settings-card"><header><span><Droplets /></span><div><h2>Hydration</h2><p>A simple daily target. No nutrition tracking.</p></div></header><div className="water-setting"><input aria-label="Daily water target" type="range" min="1500" max="4500" step="250" value={form.dailyWaterTargetMl} onChange={(event) => change("dailyWaterTargetMl", Number(event.target.value))} /><b>{(form.dailyWaterTargetMl / 1000).toFixed(2)} L</b></div></GlassCard>
    <GlassCard className="settings-card" id="appearance-settings"><header><span><Palette /></span><div><h2>Appearance</h2><p>Choose how your personal space feels.</p></div></header><div className="theme-choices">{[{ n: "Light", i: Sun }, { n: "Dark", i: Moon }, { n: "System", i: Globe2 }].map(({ n, i: Icon }) => { const active = mounted && theme === n.toLowerCase(); return <button className={active ? "active" : ""} onClick={() => setTheme(n.toLowerCase())} key={n}><Icon /><b>{n}</b>{active && <Check />}</button>; })}</div></GlassCard>
    <GlassCard className="settings-card security" id="privacy-settings"><LockKeyhole /><div><h3>Your data stays behind the API.</h3><p>Plans, tasks, habits, focus sessions, hydration, and weekly preferences are scoped to your authenticated user ID.</p></div><Database /></GlassCard>
  </div></div></main>;
}
