import { Router } from "express";
import { createHabitSchema, createTaskSchema, finishFocusSchema, hydrationSchema, onboardingSchema, patchTimeBlockSchema, rebalanceSchema, reflectionSchema, updateTaskSchema } from "@dayos/contracts";
import type { Task } from "@dayos/domain";
import { generateDayPlan, rebalanceRemainingDay } from "@dayos/planner";
import { notFound } from "../lib/errors.js";
import { findBlock, getUserData } from "../store/demo-store.js";

export const apiRouter = Router();
const user = (authUserId?: string) => getUserData(authUserId!);
const ok = <T>(res: import("express").Response, data: T, status = 200) => res.status(status).json({ data });

apiRouter.get("/me", (req, res) => ok(res, user(req.authUserId).profile));
apiRouter.patch("/me", (req, res) => { const data = user(req.authUserId); data.profile = { ...data.profile, ...req.body, id: data.profile.id, authUserId: data.profile.authUserId }; return ok(res, data.profile); });
apiRouter.post("/onboarding", (req, res) => { const input = onboardingSchema.parse(req.body); const data = user(req.authUserId); data.profile = { ...data.profile, ...input, onboardingCompleted: true }; return ok(res, data.profile); });

apiRouter.get("/tasks", (req, res) => ok(res, user(req.authUserId).tasks));
apiRouter.post("/tasks", (req, res) => { const input = createTaskSchema.parse(req.body); const item: Task = { id: crypto.randomUUID(), title: input.title, lifeArea: input.lifeArea, status: "BACKLOG", priority: input.priority, estimatedMinutes: input.estimatedMinutes, actualMinutes: 0, energyRequired: input.energyRequired, schedulingType: input.schedulingType, canSplit: input.canSplit, minimumSessionMinutes: input.minimumSessionMinutes, ...(input.description ? { description: input.description } : {}), ...(input.deadline ? { deadline: input.deadline } : {}) }; user(req.authUserId).tasks.unshift(item); return ok(res, item, 201); });
apiRouter.get("/tasks/:id", (req, res, next) => { const item = user(req.authUserId).tasks.find((task) => task.id === req.params.id); return item ? ok(res, item) : next(notFound("Task was not found.")); });
apiRouter.patch("/tasks/:id", (req, res, next) => { const data = user(req.authUserId); const index = data.tasks.findIndex((task) => task.id === req.params.id); if (index < 0) return next(notFound("Task was not found.")); const patch = Object.fromEntries(Object.entries(updateTaskSchema.parse(req.body)).filter(([, value]) => value !== undefined)); Object.assign(data.tasks[index]!, patch); return ok(res, data.tasks[index]); });
apiRouter.delete("/tasks/:id", (req, res, next) => { const data = user(req.authUserId); const index = data.tasks.findIndex((task) => task.id === req.params.id); if (index < 0) return next(notFound("Task was not found.")); data.tasks.splice(index, 1); return ok(res, { id: req.params.id }); });
for (const [path, status] of [["complete", "COMPLETED"], ["backlog", "BACKLOG"]] as const) apiRouter.post(`/tasks/:id/${path}`, (req, res, next) => { const item = user(req.authUserId).tasks.find((task) => task.id === req.params.id); if (!item) return next(notFound("Task was not found.")); item.status = status; return ok(res, item); });

apiRouter.get("/habits", (req, res) => ok(res, user(req.authUserId).habits));
apiRouter.post("/habits", (req, res) => { const input = createHabitSchema.parse(req.body); const item = { id: crypto.randomUUID(), ...input, streak: 0, completedToday: false, active: true }; user(req.authUserId).habits.unshift(item); return ok(res, item, 201); });
apiRouter.patch("/habits/:id", (req, res, next) => { const item = user(req.authUserId).habits.find((habit) => habit.id === req.params.id); if (!item) return next(notFound("Habit was not found.")); Object.assign(item, req.body); return ok(res, item); });
apiRouter.delete("/habits/:id", (req, res, next) => { const data = user(req.authUserId); const index = data.habits.findIndex((habit) => habit.id === req.params.id); if (index < 0) return next(notFound("Habit was not found.")); data.habits.splice(index, 1); return ok(res, { id: req.params.id }); });
apiRouter.post("/habits/:id/complete", (req, res, next) => { const item = user(req.authUserId).habits.find((habit) => habit.id === req.params.id); if (!item) return next(notFound("Habit was not found.")); item.completedToday = !item.completedToday; if (item.completedToday) item.streak += 1; return ok(res, item); });

apiRouter.get("/plans/today", (req, res, next) => { const data = user(req.authUserId); const today = new Intl.DateTimeFormat("en-CA", { timeZone: data.profile.timezone }).format(new Date()); const plan = data.plans.find((item) => item.date === today); return plan ? ok(res, plan) : next(notFound("Your day has not been planned yet.")); });
apiRouter.get("/plans/:date", (req, res, next) => { const plan = user(req.authUserId).plans.find((item) => item.date === req.params.date); return plan ? ok(res, plan) : next(notFound("Plan was not found.")); });
apiRouter.post("/plans/generate", (req, res) => { const data = user(req.authUserId); const date = new Intl.DateTimeFormat("en-CA", { timeZone: data.profile.timezone }).format(new Date()); const result = generateDayPlan({ date, timezone: data.profile.timezone, wakeTime: data.profile.wakeTime, sleepTime: data.profile.sleepTime, tasks: data.tasks }); const plan = { id: crypto.randomUUID(), date, status: "ACTIVE", blocks: result.blocks }; data.plans = data.plans.filter((item) => item.date !== date); data.plans.push(plan); return ok(res, plan, 201); });
apiRouter.post("/plans/:id/rebalance", (req, res, next) => { const data = user(req.authUserId); const plan = data.plans.find((item) => item.id === req.params.id); if (!plan) return next(notFound("Plan was not found.")); const input = rebalanceSchema.parse(req.body); const result = rebalanceRemainingDay({ now: input.now ?? new Date().toISOString(), currentPlan: plan.blocks, reason: input.reason }); plan.blocks = result.blocks; return ok(res, { ...plan, movedBlockIds: result.movedBlockIds }); });

apiRouter.patch("/time-blocks/:id", (req, res, next) => { const data = user(req.authUserId); const item = findBlock(data, req.params.id); if (!item) return next(notFound("Activity was not found.")); const input = patchTimeBlockSchema.parse(req.body); const overlaps = data.plans.flatMap((plan) => plan.blocks).some((other) => other.id !== item.id && new Date(input.startAt) < new Date(other.endAt) && new Date(input.endAt) > new Date(other.startAt)); if (overlaps) return res.status(409).json({ error: { code: "TIME_BLOCK_OVERLAP", message: "That time overlaps another activity." } }); Object.assign(item, input); return ok(res, item); });
for (const [path, status] of [["complete", "COMPLETED"], ["skip", "SKIPPED"]] as const) apiRouter.post(`/time-blocks/:id/${path}`, (req, res, next) => { const item = findBlock(user(req.authUserId), req.params.id); if (!item) return next(notFound("Activity was not found.")); item.status = status; return ok(res, item); });

apiRouter.post("/focus-sessions", (req, res) => { const data = user(req.authUserId); const item = { id: crypto.randomUUID(), ...(req.body.timeBlockId ? { timeBlockId: String(req.body.timeBlockId) } : {}), ...(req.body.taskId ? { taskId: String(req.body.taskId) } : {}), startedAt: new Date().toISOString(), plannedMinutes: Number(req.body.plannedMinutes ?? 90) }; data.focus.push(item); const block = item.timeBlockId ? findBlock(data, item.timeBlockId) : undefined; if (block) block.status = "ACTIVE"; return ok(res, item, 201); });
apiRouter.post("/focus-sessions/:id/finish", (req, res, next) => { const data = user(req.authUserId); const item = data.focus.find((session) => session.id === req.params.id); if (!item) return next(notFound("Focus session was not found.")); const input = finishFocusSchema.parse(req.body); item.endedAt = new Date().toISOString(); item.actualMinutes = Math.max(0, Math.round((Date.now() - new Date(item.startedAt).getTime()) / 60_000)); Object.assign(item, input); const block = item.timeBlockId ? findBlock(data, item.timeBlockId) : undefined; if (block && input.completionState === "COMPLETE") block.status = "COMPLETED"; return ok(res, item); });
apiRouter.get("/focus-sessions", (req, res) => ok(res, user(req.authUserId).focus));

apiRouter.get("/hydration/today", (req, res) => { const data = user(req.authUserId); return ok(res, { totalMl: data.hydration.reduce((sum, item) => sum + item.amountMl, 0), targetMl: data.profile.dailyWaterTargetMl }); });
apiRouter.post("/hydration", (req, res) => { const input = hydrationSchema.parse(req.body); const data = user(req.authUserId); data.hydration.push({ id: crypto.randomUUID(), amountMl: input.amountMl, loggedAt: new Date().toISOString() }); return ok(res, { totalMl: data.hydration.reduce((sum, item) => sum + item.amountMl, 0), targetMl: data.profile.dailyWaterTargetMl }, 201); });
apiRouter.post("/reflections", (req, res) => { const input = reflectionSchema.parse(req.body); const item = { id: crypto.randomUUID(), date: new Date().toISOString().slice(0, 10), dayRating: input.dayRating, energyRating: input.energyRating, focusRating: input.focusRating, ...(input.notes ? { notes: input.notes } : {}) }; user(req.authUserId).reflections.push(item); return ok(res, item, 201); });
apiRouter.get("/reflections/:date", (req, res, next) => { const item = user(req.authUserId).reflections.find((reflection) => reflection.date === req.params.date); return item ? ok(res, item) : next(notFound("Reflection was not found.")); });
apiRouter.get("/preferences", (req, res) => ok(res, user(req.authUserId).profile));
apiRouter.patch("/preferences", (req, res) => { const data = user(req.authUserId); Object.assign(data.profile, req.body); return ok(res, data.profile); });
apiRouter.get("/insights/weekly", (req, res) => { const data = user(req.authUserId); const completed = data.plans.flatMap((plan) => plan.blocks).filter((block) => block.status === "COMPLETED"); const focusMinutes = completed.filter((block) => block.type === "FOCUS").reduce((sum, block) => sum + (new Date(block.endAt).getTime() - new Date(block.startAt).getTime()) / 60_000, 0); return ok(res, { focusedMinutes: Math.round(focusMinutes), tasksCompleted: completed.length, planAdherence: 78, habitConsistency: 82, learningMinutes: 240, exerciseSessions: 4, plannedVsActual: [62, 74, 69, 82, 76, 88, 78], focusTrend: [90, 120, 75, 145, 110, 160, 130] }); });
apiRouter.get("/insights/daily/:date", (req, res) => ok(res, { date: req.params.date, completedActivities: 7, plannedActivities: 9, focusedMinutes: 320 }));
