"use client";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, Brain, Check, CheckCircle2, Circle, Clock3, Coffee, Dumbbell, GraduationCap, Heart, Leaf, LockKeyhole, Moon, Palette, Play, Plus, RotateCcw, Sparkles, Square, Utensils, Waves, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useDayOS } from "@/components/providers";
import { GlassCard, GlassPill } from "@/components/glass/glass";
import { Button } from "@/components/ui/button";
import type { TimeBlock, TimeBlockType } from "@dayos/domain";

const icons: Record<TimeBlockType, typeof Brain> = { FOCUS:Brain,TASK:CheckCircle2,HABIT:Leaf,MEAL:Utensils,EXERCISE:Dumbbell,LEARNING:GraduationCap,READING:GraduationCap,BREAK:Coffee,EVENT:Clock3,FREE:Waves,HOBBY:Palette,FAMILY:Heart,MEDITATION:Sparkles,SLEEP:Moon };
const formatTime=(value:string)=>new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
const duration=(block:TimeBlock)=>Math.round((new Date(block.endAt).getTime()-new Date(block.startAt).getTime())/60000);
function useLiveNow(intervalMs:number){const [now,setNow]=useState<number|null>(null);useEffect(()=>{const tick=()=>setNow(Date.now());tick();const id=window.setInterval(tick,intervalMs);return()=>window.clearInterval(id);},[intervalMs]);return now;}
function LiveCountdown({ endAt }: { endAt:string }) { const now=useLiveNow(1000); if(now===null)return <strong className="countdown">--:--:--</strong>; const seconds=Math.max(0,Math.round((new Date(endAt).getTime()-now)/1000)); const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60; return <strong className="countdown">{[h,m,s].map((v)=>String(v).padStart(2,"0")).join(":")}</strong>; }
function CurrentTimeLine({block}:{block:TimeBlock}){const now=useLiveNow(30_000);if(now===null)return null;const start=new Date(block.startAt).getTime();const end=new Date(block.endAt).getTime();const progress=Math.max(4,Math.min(96,(now-start)/(end-start)*100));const time=new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(now)); return <div className="current-line" style={{top:`${progress}%`}}><span/ ><b>{time}</b><span/></div>}

export function TodayView() {
  const { profile,blocks,water,logWater,completeBlock,rebalance,startFocus,finishFocus }=useDayOS(); const [focus,setFocus]=useState<TimeBlock|null>(null); const [focusSession,setFocusSession]=useState<string|null>(null); const [finish,setFinish]=useState(false); const [notice,setNotice]=useState<string|null>(null); const [focusError,setFocusError]=useState<string|null>(null); const [focusBusy,setFocusBusy]=useState(false);
  const sorted=useMemo(()=>[...blocks].sort((a,b)=>a.startAt.localeCompare(b.startAt)),[blocks]); const now=useLiveNow(30_000); const active=now===null?(sorted.find((item)=>item.status==="ACTIVE")??sorted.find((item)=>item.status!=="COMPLETED")):(sorted.find((item)=>new Date(item.startAt).getTime()<=now&&new Date(item.endAt).getTime()>now)??sorted.find((item)=>new Date(item.startAt).getTime()>now&&item.status!=="COMPLETED")); const next=active?sorted.find((item)=>new Date(item.startAt)>new Date(active.endAt)):undefined;
  const currentDate=now===null?null:new Date(now); const timeZone=profile?.timezone; const date=currentDate?new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric",...(timeZone?{timeZone}:{})}).format(currentDate):"Today"; const hour=currentDate?Number(new Intl.DateTimeFormat("en",{hour:"2-digit",hourCycle:"h23",...(timeZone?{timeZone}:{})}).format(currentDate)):null; const greeting=hour===null?"Hello":hour<12?"Good morning":hour<18?"Good afternoon":"Good evening";
  const intentional=useMemo(()=>sorted.filter((block)=>block.type!=="FREE"&&block.type!=="SLEEP"),[sorted]);
  const balance=useMemo(()=>[{n:"Work",c:"work",area:"WORK"},{n:"Learning",c:"learn",area:"LEARNING"},{n:"Health",c:"health",area:"HEALTH"},{n:"Personal",c:"personal",area:"PERSONAL"},{n:"Recovery",c:"recover",area:"RECOVERY"}].map((item)=>({...item,v:intentional.filter((block)=>block.lifeArea===item.area).reduce((sum,block)=>sum+duration(block),0)})),[intentional]);
  const completed=intentional.filter((item)=>item.status==="COMPLETED").length; const firstName=profile?.displayName.split(" ")[0]??"there";
  const beginFocus=async(block:TimeBlock)=>{setFocusError(null);try {const id=await startFocus(block);setFocusSession(id);setFocus(block);} catch(reason) {setFocusError(reason instanceof Error?reason.message:"Focus could not start.");}};
  const endFocus=async(state:"COMPLETE"|"PARTIAL"|"NOT_COMPLETE",rating:number)=>{if(!focusSession||focusBusy)return;setFocusBusy(true);setFocusError(null);try {await finishFocus(focusSession,state,rating);setFocus(null);setFocusSession(null);setFinish(false);} catch(reason) {setFocusError(reason instanceof Error?reason.message:"Focus could not be saved.");} finally {setFocusBusy(false);}};
  const adjust=async()=>{setNotice(null);try {await rebalance();setNotice("Today changed. Your remaining schedule was adjusted.");} catch(reason) {setNotice(reason instanceof Error?reason.message:"Your schedule could not be adjusted.");} window.setTimeout(()=>setNotice(null),3200);};
  return <main className="workspace today-workspace"><header className="page-heading"><div><span className="overline">{date.toUpperCase()}</span><h1>{greeting}, {firstName}.</h1><p>{sorted.length?"Only the present window matters. DayOS is holding the rest of the day for you.":"Add a task and build a plan that fits your day."}</p></div><GlassPill className="day-status"><span/> {completed===intentional.length&&intentional.length?"Complete":"On track"} <small>{completed} of {intentional.length} activities complete</small></GlassPill></header>
    {focusError&&!focus&&<p className="form-error" role="alert">{focusError}</p>}<div className="today-grid"><section className="timeline-panel"><div className="section-title"><div><span className="overline">TODAY’S TIMELINE</span><h2>Shape of your day</h2></div><Button variant="ghost" size="sm" onClick={()=>void adjust()}><RotateCcw size={15}/> Rebalance</Button></div>
      <AnimatePresence>{notice&&<motion.div className="rebalance-notice" role="status" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><Sparkles/> {notice}</motion.div>}</AnimatePresence>
      <div className="timeline">{sorted.map((block)=>{const Icon=icons[block.type]; const current=block.id===active?.id; const live=now!==null&&current&&new Date(block.startAt).getTime()<=now&&new Date(block.endAt).getTime()>now; const focusable=["FOCUS","TASK","LEARNING","READING"].includes(block.type)&&block.status!=="COMPLETED"; return <motion.article layout key={block.id} className={`timeline-row ${current?"current":""} ${block.status.toLowerCase()} type-${block.type.toLowerCase()}`} transition={{type:"spring",stiffness:260,damping:28}}><time>{formatTime(block.startAt)}</time><div className="rail"><i/>{live&&<CurrentTimeLine block={block}/>}</div><GlassCard className="time-block"><div className="block-icon"><Icon/></div><div className="block-copy"><div><h3>{block.title}</h3>{block.locked&&<LockKeyhole/>}</div><p>{block.description??`${block.type.charAt(0)+block.type.slice(1).toLowerCase()} · ${duration(block)} min`}</p><small>{formatTime(block.startAt)} – {formatTime(block.endAt)} {block.flexibility==="FLEXIBLE"&&<span>Flexible</span>}</small></div>{focusable&&<button className="block-focus" onClick={()=>void beginFocus(block)} aria-label={`Focus ${block.title}`}><Play/></button>}{block.status==="COMPLETED"?<button className="block-check done" aria-label="Completed"><Check/></button>:<button className="block-check" onClick={()=>void completeBlock(block.id)} aria-label={`Complete ${block.title}`}><Circle/></button>}</GlassCard></motion.article>})}</div>
    </section><aside className="context-panel">{active?<GlassCard className="now-card"><div className="now-top"><span className="overline"><i/> RIGHT NOW</span></div><div className="now-symbol"><Brain/></div><span className="now-type">{active.type==="FOCUS"?"Deep Work":active.type}</span><h2>{active.title}</h2><p>{active.description??"One thing at a time."}</p><div className="now-time"><span>{formatTime(active.startAt)} – {formatTime(active.endAt)}</span><LiveCountdown endAt={active.endAt}/><small>remaining</small></div>{["FOCUS","TASK","LEARNING","READING"].includes(active.type)?<Button size="lg" className="full" onClick={()=>void beginFocus(active)}><Play size={16} fill="currentColor"/> {active.status==="ACTIVE"?"Continue focus":"Start focus"}</Button>:<Button size="lg" className="full" onClick={()=>void completeBlock(active.id)}><Check/> Mark complete</Button>}<div className="now-actions"><button onClick={()=>void completeBlock(active.id)}><Check/> Complete</button><Link href="/app/calendar">Adjust schedule</Link></div></GlassCard>:<GlassCard className="now-card now-empty"><div className="now-symbol"><CheckCircle2/></div><span className="overline">DAY COMPLETE</span><h2>Nothing else is waiting.</h2><p>Your remaining time is yours.</p></GlassCard>}
      {next&&<GlassCard className="next-card"><span className="overline">NEXT</span><div><span className="next-icon"><Coffee/></span><div><h3>{next.title}</h3><p>{formatTime(next.startAt)} · {duration(next)} min</p></div><ArrowRight/></div></GlassCard>}
      <GlassCard className="water-card"><div className="widget-title"><div><span className="water-drop"><Waves/></span><div><span className="overline">WATER</span><h3>{(water.totalMl/1000).toFixed(2)} <small>/ {(water.targetMl/1000).toFixed(1)} L</small></h3></div></div><span>{Math.round(water.totalMl/water.targetMl*100)}%</span></div><div className="water-progress"><motion.i animate={{width:`${Math.min(100,water.totalMl/water.targetMl*100)}%`}}/></div><div className="water-buttons"><button onClick={()=>void logWater(250)}><Plus/>250 ml</button><button onClick={()=>void logWater(500)}><Plus/>500 ml</button></div></GlassCard>
      <GlassCard className="balance-card"><span className="overline">DAILY BALANCE</span><div className="balance-list">{balance.map((item)=><div key={item.n}><span>{item.n}</span><i><b className={item.c} style={{width:`${item.v/3.2}%`}}/></i><strong>{Math.floor(item.v/60)}h {item.v%60?`${item.v%60}m`:""}</strong></div>)}</div></GlassCard>
    </aside></div><ReflectionCard />
    <AnimatePresence>{focus&&<FocusMode block={focus} finishing={finish} busy={focusBusy} error={focusError} onFinish={()=>setFinish(true)} onClose={()=>void endFocus("PARTIAL",3)} onComplete={(state,rating)=>void endFocus(state,rating)}/>}</AnimatePresence>
  </main>;
}

function ReflectionCard() {
  const { reflection, saveReflection } = useDayOS();
  const [message, setMessage] = useState<string | null>(null);
  return <ReflectionForm key={reflection?.id ?? "new"} reflection={reflection} saveReflection={saveReflection} message={message} setMessage={setMessage} />;
}

function ReflectionForm({ reflection, saveReflection, message, setMessage }: { reflection: ReturnType<typeof useDayOS>["reflection"]; saveReflection: ReturnType<typeof useDayOS>["saveReflection"]; message: string | null; setMessage(value: string | null): void }) {
  const [dayRating, setDayRating] = useState(reflection?.dayRating ?? 3);
  const [energyRating, setEnergyRating] = useState(reflection?.energyRating ?? 3);
  const [focusRating, setFocusRating] = useState(reflection?.focusRating ?? 3);
  const [notes, setNotes] = useState(reflection?.notes ?? "");
  const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setMessage(null); try { await saveReflection({ dayRating, energyRating, focusRating, notes }); setMessage("Reflection saved for today."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Reflection could not be saved."); } finally { setSaving(false); } };
  return <GlassCard className="reflection-card"><span className="overline">END-OF-DAY CHECK-IN</span><h2>Make tomorrow more personal.</h2><p>Record how today actually felt. You can update this once your day changes.</p><div className="reflection-ratings">{([{ label: "Day", value: dayRating, set: setDayRating }, { label: "Energy", value: energyRating, set: setEnergyRating }, { label: "Focus", value: focusRating, set: setFocusRating }] as const).map(({ label, value, set }) => <div key={label}><span>{label}</span><div>{[1, 2, 3, 4, 5].map((rating) => <button type="button" className={rating === value ? "active" : ""} onClick={() => set(rating)} aria-label={`${label} ${rating} of 5`} key={rating}>{rating}</button>)}</div></div>)}</div><label>What would help tomorrow?<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={4000} placeholder="A small note for your future self" /></label><div className="reflection-footer"><Button disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : reflection ? "Update reflection" : "Save reflection"}</Button>{message && <span role="status">{message}</span>}</div></GlassCard>;
}

function FocusMode({block,finishing,busy,error,onFinish,onClose,onComplete}:{block:TimeBlock;finishing:boolean;busy:boolean;error:string|null;onFinish():void;onClose():void;onComplete(state:"COMPLETE"|"PARTIAL"|"NOT_COMPLETE",rating:number):void}) {
  const [completion,setCompletion]=useState<"COMPLETE"|"PARTIAL"|"NOT_COMPLETE">("COMPLETE");
  return <motion.div className="focus-mode" initial={{opacity:0,scale:1.04,filter:"blur(18px)"}} animate={{opacity:1,scale:1,filter:"blur(0px)"}} exit={{opacity:0,scale:1.035,filter:"blur(16px)"}} transition={{type:"spring",stiffness:180,damping:25,mass:.85}}><button className="focus-close" disabled={busy} onClick={onClose} aria-label="Save and leave focus mode"><X/></button><div className="focus-orb one"/><div className="focus-orb two"/>{!finishing?<motion.div className="focus-content" layoutId={`block-${block.id}`} transition={{type:"spring",stiffness:210,damping:26}}><span className="overline">DEEP WORK</span><h1>{block.title}</h1><p>{block.description??"Stay with the work in front of you."}</p><LiveCountdown endAt={block.endAt}/><small>Stay focused.</small><div><Button size="lg" onClick={onFinish}><Square fill="currentColor"/> Finish</Button></div>{error&&<p className="form-error" role="alert">{error}</p>}</motion.div>:<motion.div className="finish-card glass glass-depth-3" initial={{opacity:0,y:28,scale:.92,filter:"blur(12px)"}} animate={{opacity:1,y:0,scale:1,filter:"blur(0px)"}} transition={{type:"spring",stiffness:280,damping:27,mass:.78}}><span className="overline">SESSION COMPLETE</span><h2>Did you complete what you planned?</h2><div className="finish-choices"><button className={completion==="COMPLETE"?"active":""} onClick={()=>setCompletion("COMPLETE")}><CheckCircle2/>Completed</button><button className={completion==="PARTIAL"?"active":""} onClick={()=>setCompletion("PARTIAL")}><Circle/>Partially</button><button className={completion==="NOT_COMPLETE"?"active":""} onClick={()=>setCompletion("NOT_COMPLETE")}><RotateCcw/>Not yet</button></div><h3>How focused were you?</h3><div className="rating">{[1,2,3,4,5].map((n)=><button disabled={busy} onClick={()=>onComplete(completion,n)} key={n}>{n}</button>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}</motion.div>}</motion.div>;
}
