/* eslint-disable react-hooks/purity */
"use client";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, Brain, Check, CheckCircle2, Circle, Clock3, Coffee, Dumbbell, GraduationCap, GripVertical, Leaf, LockKeyhole, MoreHorizontal, Pause, Play, Plus, RotateCcw, SkipForward, Sparkles, Square, TimerReset, Utensils, Waves, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useDayOS } from "@/components/providers";
import { GlassCard, GlassPill } from "@/components/glass/glass";
import { Button } from "@/components/ui/button";
import type { TimeBlock } from "@dayos/domain";

const icons = { FOCUS:Brain,TASK:CheckCircle2,HABIT:Leaf,MEAL:Utensils,EXERCISE:Dumbbell,LEARNING:GraduationCap,READING:GraduationCap,BREAK:Coffee,EVENT:Clock3,FREE:Waves };
const formatTime=(value:string)=>new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));
const duration=(block:TimeBlock)=>Math.round((new Date(block.endAt).getTime()-new Date(block.startAt).getTime())/60000);
function LiveCountdown({ endAt }: { endAt:string }) { const [now,setNow]=useState(Date.now()); useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000); return ()=>window.clearInterval(id);},[]); const seconds=Math.max(0,Math.round((new Date(endAt).getTime()-now)/1000)); const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60; return <strong className="countdown">{[h,m,s].map((v)=>String(v).padStart(2,"0")).join(":")}</strong>; }
function CurrentTimeLine(){const time=new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date()); return <div className="current-line"><span/ ><b>{time}</b><span/></div>}

export function TodayView() {
  const { blocks,water,logWater,completeBlock,rebalance }=useDayOS(); const [focus,setFocus]=useState<TimeBlock|null>(null); const [finish,setFinish]=useState(false); const [notice,setNotice]=useState(false);
  const sorted=useMemo(()=>[...blocks].sort((a,b)=>a.startAt.localeCompare(b.startAt)),[blocks]); const active=sorted.find((item)=>item.status==="ACTIVE")??sorted.find((item)=>new Date(item.endAt)>new Date()&&item.status!=="COMPLETED")??sorted[0]; const next=active?sorted[sorted.indexOf(active)+1]:undefined;
  const date=new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date()); const hour=new Date().getHours();
  const balance=[{n:"Work",v:320,c:"work"},{n:"Learning",v:100,c:"learn"},{n:"Health",v:90,c:"health"},{n:"Personal",v:45,c:"personal"},{n:"Recovery",v:115,c:"recover"}];
  return <main className="workspace today-workspace"><header className="page-heading"><div><span className="overline">{date.toUpperCase()}</span><h1>Good {hour<12?"morning":hour<18?"afternoon":"evening"}, Alex.</h1><p>A focused start, with room to breathe later.</p></div><GlassPill className="day-status"><span/> On track <small>2 of 9 complete</small></GlassPill></header>
    <div className="today-grid"><section className="timeline-panel"><div className="section-title"><div><span className="overline">TODAY’S TIMELINE</span><h2>Shape of your day</h2></div><Button variant="ghost" size="sm" onClick={()=>{void rebalance();setNotice(true);setTimeout(()=>setNotice(false),3200)}}><RotateCcw size={15}/> Rebalance</Button></div>
      <AnimatePresence>{notice&&<motion.div className="rebalance-notice" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><Sparkles/> Today changed. Your remaining schedule was adjusted.</motion.div>}</AnimatePresence>
      <div className="timeline">{sorted.map((block,index)=>{const Icon=icons[block.type]; const current=block.id===active?.id; return <motion.article layout key={block.id} className={`timeline-row ${current?"current":""} ${block.status.toLowerCase()} type-${block.type.toLowerCase()}`} transition={{type:"spring",stiffness:260,damping:28}}><time>{formatTime(block.startAt)}</time><div className="rail"><i/>{index===Math.max(1,sorted.findIndex((item)=>new Date(item.startAt)>new Date()))&&<CurrentTimeLine/>}</div><GlassCard className="time-block"><div className="block-icon"><Icon/></div><div className="block-copy"><div><h3>{block.title}</h3>{block.locked&&<LockKeyhole/>}</div><p>{block.description??`${block.type.charAt(0)+block.type.slice(1).toLowerCase()} · ${duration(block)} min`}</p><small>{formatTime(block.startAt)} – {formatTime(block.endAt)} {block.flexibility==="FLEXIBLE"&&<span>Flexible</span>}</small></div>{block.status==="COMPLETED"?<button className="block-check done" aria-label="Completed"><Check/></button>:<button className="block-check" onClick={()=>void completeBlock(block.id)} aria-label={`Complete ${block.title}`}><Circle/></button>}<button className="drag-handle" aria-label="Move activity"><GripVertical/></button></GlassCard></motion.article>})}</div>
    </section><aside className="context-panel">{active&&<GlassCard className="now-card"><div className="now-top"><span className="overline"><i/> RIGHT NOW</span><button aria-label="More actions"><MoreHorizontal/></button></div><div className="now-symbol"><Brain/></div><span className="now-type">{active.type==="FOCUS"?"Deep Work":active.type}</span><h2>{active.title}</h2><p>{active.description??"One thing at a time."}</p><div className="now-time"><span>{formatTime(active.startAt)} – {formatTime(active.endAt)}</span><LiveCountdown endAt={active.endAt}/><small>remaining</small></div><Button size="lg" className="full" onClick={()=>setFocus(active)}><Play size={16} fill="currentColor"/> {active.status==="ACTIVE"?"Continue focus":"Start focus"}</Button><div className="now-actions"><button onClick={()=>void completeBlock(active.id)}><Check/> Complete</button><button><SkipForward/> Delay</button><button><TimerReset/> Extend</button></div></GlassCard>}
      {next&&<GlassCard className="next-card"><span className="overline">NEXT</span><div><span className="next-icon"><Coffee/></span><div><h3>{next.title}</h3><p>{formatTime(next.startAt)} · {duration(next)} min</p></div><ArrowRight/></div></GlassCard>}
      <GlassCard className="water-card"><div className="widget-title"><div><span className="water-drop"><Waves/></span><div><span className="overline">WATER</span><h3>{(water.totalMl/1000).toFixed(2)} <small>/ {(water.targetMl/1000).toFixed(1)} L</small></h3></div></div><span>{Math.round(water.totalMl/water.targetMl*100)}%</span></div><div className="water-progress"><motion.i animate={{width:`${Math.min(100,water.totalMl/water.targetMl*100)}%`}}/></div><div className="water-buttons"><button onClick={()=>void logWater(250)}><Plus/>250 ml</button><button onClick={()=>void logWater(500)}><Plus/>500 ml</button></div></GlassCard>
      <GlassCard className="balance-card"><span className="overline">DAILY BALANCE</span><div className="balance-list">{balance.map((item)=><div key={item.n}><span>{item.n}</span><i><b className={item.c} style={{width:`${item.v/3.2}%`}}/></i><strong>{Math.floor(item.v/60)}h {item.v%60?`${item.v%60}m`:""}</strong></div>)}</div></GlassCard>
    </aside></div>
    <AnimatePresence>{focus&&<FocusMode block={focus} finishing={finish} onFinish={()=>setFinish(true)} onClose={()=>{setFocus(null);setFinish(false)}} onComplete={()=>{void completeBlock(focus.id);setFocus(null);setFinish(false)}}/>}</AnimatePresence>
  </main>;
}

function FocusMode({block,finishing,onFinish,onClose,onComplete}:{block:TimeBlock;finishing:boolean;onFinish():void;onClose():void;onComplete():void}) {
  return <motion.div className="focus-mode" initial={{opacity:0,scale:1.04,filter:"blur(18px)"}} animate={{opacity:1,scale:1,filter:"blur(0px)"}} exit={{opacity:0,scale:1.035,filter:"blur(16px)"}} transition={{type:"spring",stiffness:180,damping:25,mass:.85}}><button className="focus-close" onClick={onClose}><X/></button><div className="focus-orb one"/><div className="focus-orb two"/>{!finishing?<motion.div className="focus-content" layoutId={`block-${block.id}`} transition={{type:"spring",stiffness:210,damping:26}}><span className="overline">DEEP WORK</span><h1>{block.title}</h1><p>{block.description??"Stay with the work in front of you."}</p><LiveCountdown endAt={block.endAt}/><small>Stay focused.</small><div><Button variant="secondary" size="lg"><Pause/> Pause</Button><Button size="lg" onClick={onFinish}><Square fill="currentColor"/> Finish</Button></div></motion.div>:<motion.div className="finish-card glass glass-depth-3" initial={{opacity:0,y:28,scale:.92,filter:"blur(12px)"}} animate={{opacity:1,y:0,scale:1,filter:"blur(0px)"}} transition={{type:"spring",stiffness:280,damping:27,mass:.78}}><span className="overline">SESSION COMPLETE</span><h2>Did you complete what you planned?</h2><div className="finish-choices"><button onClick={onComplete}><CheckCircle2/>Completed</button><button onClick={onComplete}><Circle/>Partially</button><button onClick={onComplete}><RotateCcw/>Not yet</button></div><h3>How focused were you?</h3><div className="rating">{[1,2,3,4,5].map((n)=><button onClick={onComplete} key={n}>{n}</button>)}</div></motion.div>}</motion.div>;
}
