"use client";
import { DndContext, PointerSensor, useDraggable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { addDays, format } from "date-fns";
import { ChevronLeft, ChevronRight, GripVertical, LockKeyhole, Plus } from "lucide-react";
import { useState } from "react";
import type { TimeBlock } from "@dayos/domain";
import { useDayOS } from "@/components/providers";
import { Button } from "@/components/ui/button";

const hourStart=7;const formatTime=(v:string)=>format(new Date(v),"HH:mm");
function DraggableBlock({block,day=0}:{block:TimeBlock;day?:number}){const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:`${block.id}-${day}`,disabled:block.flexibility==="FIXED"});const start=new Date(block.startAt);const minutes=(start.getHours()-hourStart)*60+start.getMinutes();const height=Math.max(34,(new Date(block.endAt).getTime()-start.getTime())/60000*.9);return <article ref={setNodeRef} style={{top:minutes*.9+4,height,transform:CSS.Translate.toString(transform),opacity:isDragging?.55:1}} className={`calendar-block type-${block.type.toLowerCase()} ${block.flexibility==="FIXED"?"locked":""}`} {...attributes} {...listeners}><span>{block.flexibility==="FIXED"?<LockKeyhole/>:<GripVertical/>}</span><div><b>{block.title}</b><small>{formatTime(block.startAt)}–{formatTime(block.endAt)}</small></div></article>}
export function CalendarView(){const {blocks}=useDayOS();const [view,setView]=useState<"Day"|"Week">("Week");const [anchor,setAnchor]=useState(new Date());const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}));const onDragEnd=(event:DragEndEvent)=>{void event;/* Server validates final timestamp in the integrated editor. */};const days=view==="Day"?[anchor]:Array.from({length:7},(_,i)=>addDays(anchor,i));return <main className="workspace calendar-workspace"><header className="page-heading compact"><div><span className="overline">TIME, MADE VISIBLE</span><h1>Calendar</h1><p>Move the flexible. Protect the fixed.</p></div><Button><Plus/> Add event</Button></header><div className="calendar-toolbar"><div className="calendar-nav"><button onClick={()=>setAnchor(addDays(anchor,view==="Day"?-1:-7))}><ChevronLeft/></button><button onClick={()=>setAnchor(new Date())}>Today</button><button onClick={()=>setAnchor(addDays(anchor,view==="Day"?1:7))}><ChevronRight/></button><h2>{format(anchor,"MMMM yyyy")}</h2></div><div className="segmented"><button className={view==="Day"?"active":""} onClick={()=>setView("Day")}>Day</button><button className={view==="Week"?"active":""} onClick={()=>setView("Week")}>Week</button></div></div><DndContext sensors={sensors} onDragEnd={onDragEnd}><div className={`calendar-grid ${view.toLowerCase()}`}><div className="calendar-hours"><span/><div>{Array.from({length:16},(_,i)=><time key={i}>{String(i+hourStart).padStart(2,"0")}:00</time>)}</div></div>{days.map((day,index)=><section key={day.toISOString()}><header className={format(day,"yyyy-MM-dd")===format(new Date(),"yyyy-MM-dd")?"today":""}><span>{format(day,"EEE")}</span><b>{format(day,"d")}</b></header><div className="calendar-column">{Array.from({length:16},(_,i)=><i key={i}/>) }{(view==="Day"||index===new Date().getDay()-1||index===0)&&blocks.filter((item)=>item.type!=="FREE").map((block)=><DraggableBlock key={`${block.id}-${index}`} block={block} day={index}/>)}</div></section>)}</div></DndContext><div className="calendar-legend"><span><i className="fixed"/> Fixed</span><span><i className="flexible"/> Flexible</span><span><i className="window"/> Flexible window</span><p>Drag flexible blocks to preview a move. Conflicts are validated before saving.</p></div></main>}
