"use client";

import { AnimatePresence, motion } from "motion/react";
import { ArrowLeft, ArrowRight, BookOpen, BriefcaseBusiness, Brain, Dumbbell, Heart, Moon, PersonStanding, Sparkles, Sun, Users, Waves } from "lucide-react";
import type { RoutineWindowPreference } from "@dayos/domain";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
import { useDayOS } from "@/components/providers";
import { Button } from "@/components/ui/button";

const spaces = [{label:"Work",icon:BriefcaseBusiness},{label:"Learning",icon:BookOpen},{label:"Exercise",icon:Dumbbell},{label:"Reading",icon:BookOpen},{label:"Personal projects",icon:PersonStanding},{label:"Family",icon:Users},{label:"Recovery",icon:Waves}];
const improvements = ["Focus","Consistency","Learning","Health","Balance","Less wasted time","Better routines"];
const exerciseValues = { Morning: "MORNING", Afternoon: "AFTERNOON", Evening: "EVENING", "No preference": "NO_PREFERENCE" } as const;
const dayLabels = ["S","M","T","W","T","F","S"];
const defaultRoutines: RoutineWindowPreference[] = [
  {id:"work",title:"Work / study commitments",kind:"WORK",days:[1,2,3,4,5],start:"09:00",end:"18:00",durationMinutes:540,flexibility:"FIXED",active:true},
  {id:"movement",title:"Workout / movement",kind:"EXERCISE",days:[1,2,4,6],start:"18:00",end:"19:00",durationMinutes:45,flexibility:"PREFERRED",active:true},
  {id:"learning",title:"Learning / skill practice",kind:"LEARNING",days:[1,2,3,4,5,6],start:"19:30",end:"20:30",durationMinutes:45,flexibility:"PREFERRED",active:true},
  {id:"hobby",title:"Hobby / personal project",kind:"HOBBY",days:[0,3,6],start:"16:00",end:"17:30",durationMinutes:60,flexibility:"PREFERRED",active:true},
  {id:"family",title:"Family / relationships",kind:"FAMILY",days:[0,1,2,3,4,5,6],start:"20:30",end:"21:30",durationMinutes:45,flexibility:"PREFERRED",active:true},
  {id:"quiet",title:"Meditation / quiet start",kind:"MEDITATION",days:[0,1,2,3,4,5,6],start:"07:00",end:"07:30",durationMinutes:15,flexibility:"PREFERRED",active:true},
  {id:"wind-down",title:"Evening wind-down",kind:"WIND_DOWN",days:[0,1,2,3,4,5,6],start:"22:15",end:"22:45",durationMinutes:30,flexibility:"FIXED",active:true}
];

export function OnboardingFlow() {
  const router = useRouter(); const { completeOnboarding } = useDayOS();
  const [step, setStep] = useState(0); const [wake, setWake] = useState("07:00"); const [sleep, setSleep] = useState("23:00"); const [workStart, setWorkStart] = useState("09:00"); const [workEnd, setWorkEnd] = useState("18:00"); const [variableWork, setVariableWork] = useState(false);
  const [selected, setSelected] = useState(["Work","Learning","Exercise","Recovery"]); const [exercise, setExercise] = useState<keyof typeof exerciseValues>("Evening"); const [water, setWater] = useState(3000); const [goals, setGoals] = useState(["Focus","Balance"]);
  const [routines,setRoutines]=useState(defaultRoutines); const [freeUses,setFreeUses]=useState(["Family","Meditation","Learning","Rest"]); const [planningStyle,setPlanningStyle]=useState<"STRUCTURED"|"BALANCED"|"SPACIOUS">("BALANCED");
  const [meals, setMeals] = useState({ breakfast:{start:"08:00",end:"09:00"}, lunch:{start:"13:00",end:"14:30"}, dinner:{start:"19:00",end:"20:30"} }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const toggle = (list: string[], value: string, update: (next:string[])=>void) => update(list.includes(value) ? list.filter((item)=>item!==value) : [...list,value]);
  const updateMeal = (name: keyof typeof meals, field: "start" | "end", value: string) => setMeals((current) => ({ ...current, [name]: { ...current[name], [field]: value } }));
  const updateRoutine=(id:string,patch:Partial<RoutineWindowPreference>)=>setRoutines((items)=>items.map((item)=>item.id===id?{...item,...patch}:item));
  const toggleRoutineDay=(id:string,day:number)=>setRoutines((items)=>items.map((item)=>item.id!==id?item:{...item,days:item.days.includes(day)?item.days.filter((value)=>value!==day):[...item.days,day].sort()}));
  const finish = async () => { setSaving(true); setError(null); try { await completeOnboarding({ timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", wakeTime: wake, sleepTime: sleep, workStartTime: workStart, workEndTime: workEnd, dailyWaterTargetMl: water, priorities: selected, improvementGoals: goals, exercisePreference: exerciseValues[exercise], variableWorkHours: variableWork, mealWindows: meals, routineWindows:routines.map((item)=>item.id==="work"?{...item,start:workStart,end:workEnd}:item), freeTime:{preferredUses:freeUses,minimumOpenWindowMinutes:planningStyle==="STRUCTURED"?90:60,dailyUnscheduledMinutes:planningStyle==="STRUCTURED"?30:planningStyle==="SPACIOUS"?90:60}, planningStyle }); router.replace("/app/today"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Your first plan could not be saved."); } finally { setSaving(false); } };
  const steps = [
    <div className="onboard-question" key="wake"><Sun className="question-icon"/><span className="overline">BEGIN YOUR DAY</span><h1>When do you normally wake up?</h1><p>This sets the earliest edge of your schedule.</p><input className="time-input" aria-label="Wake time" type="time" value={wake} onChange={(event)=>setWake(event.target.value)}/></div>,
    <div className="onboard-question" key="sleep"><Moon className="question-icon"/><span className="overline">PROTECT RECOVERY</span><h1>When would you like to sleep?</h1><p>DayOS never schedules beyond this boundary.</p><input className="time-input" aria-label="Sleep time" type="time" value={sleep} onChange={(event)=>setSleep(event.target.value)}/></div>,
    <div className="onboard-question wide" key="space"><span className="overline">YOUR PRIORITIES</span><h1>What deserves space in your day?</h1><p>Choose everything you want the plan to protect.</p><div className="choice-grid">{spaces.map(({label,icon:Icon})=><button type="button" key={label} className={selected.includes(label)?"choice active":"choice"} onClick={()=>toggle(selected,label,setSelected)}><Icon/>{label}</button>)}</div></div>,
    <div className="onboard-question" key="work"><BriefcaseBusiness className="question-icon"/><span className="overline">YOUR COMMITMENTS</span><h1>What are your usual work hours?</h1><div className="time-range"><input aria-label="Work begins" type="time" value={workStart} onChange={(event)=>setWorkStart(event.target.value)}/><ArrowRight/><input aria-label="Work ends" type="time" value={workEnd} onChange={(event)=>setWorkEnd(event.target.value)}/></div><label className="check-row"><input type="checkbox" checked={variableWork} onChange={(event)=>setVariableWork(event.target.checked)}/> My work hours vary</label></div>,
    <div className="onboard-question routine-question" key="routines"><Brain className="question-icon"/><span className="overline">MAP YOUR REAL WEEK</span><h1>What usually belongs in each window?</h1><p>Rename anything, set exact times, choose its days, or turn it off. DayOS will repeat this rhythm without making you remember it.</p><div className="routine-editor">{routines.map((routine)=><div className={routine.active?"routine-row":"routine-row inactive"} key={routine.id}><label className="routine-toggle"><input type="checkbox" checked={routine.active} onChange={(event)=>updateRoutine(routine.id,{active:event.target.checked})}/><span/></label><div className="routine-main"><input aria-label={`${routine.kind} title`} value={routine.title} onChange={(event)=>updateRoutine(routine.id,{title:event.target.value})}/><small>{routine.kind.replace("_"," ")}</small></div><div className="routine-times"><input aria-label={`${routine.kind} starts`} type="time" value={routine.id==="work"?workStart:routine.start} onChange={(event)=>routine.id==="work"?setWorkStart(event.target.value):updateRoutine(routine.id,{start:event.target.value})}/><span>–</span><input aria-label={`${routine.kind} ends`} type="time" value={routine.id==="work"?workEnd:routine.end} onChange={(event)=>routine.id==="work"?setWorkEnd(event.target.value):updateRoutine(routine.id,{end:event.target.value})}/></div><div className="routine-days">{dayLabels.map((label,day)=><button type="button" aria-label={`${routine.title} ${day}`} className={routine.days.includes(day)?"active":""} onClick={()=>toggleRoutineDay(routine.id,day)} key={`${routine.id}-${day}`}>{label}</button>)}</div></div>)}</div></div>,
    <div className="onboard-question wide" key="exercise"><Dumbbell className="question-icon"/><span className="overline">MOVE WELL</span><h1>When does exercise feel best?</h1><div className="segmented big">{Object.keys(exerciseValues).map((item)=><button type="button" className={exercise===item?"active":""} onClick={()=>setExercise(item as keyof typeof exerciseValues)} key={item}>{item}</button>)}</div></div>,
    <div className="onboard-question wide" key="meals"><span className="overline">MEAL WINDOWS</span><h1>Keep time open to refuel.</h1><p>These are flexible windows, not rigid alarms.</p><div className="meal-list">{(["breakfast","lunch","dinner"] as const).map((name)=><div key={name}><b>{name.charAt(0).toUpperCase()+name.slice(1)}</b><input aria-label={`${name} starts`} type="time" value={meals[name].start} onChange={(event)=>updateMeal(name,"start",event.target.value)}/><span>to</span><input aria-label={`${name} ends`} type="time" value={meals[name].end} onChange={(event)=>updateMeal(name,"end",event.target.value)}/></div>)}</div></div>,
    <div className="onboard-question wide" key="free"><Sparkles className="question-icon"/><span className="overline">INTENTIONAL OPEN TIME</span><h1>When time is abundant, what should DayOS protect it for?</h1><p>Open windows remain visible. They are not automatically filled with more work.</p><div className="segmented big planning-style">{(["STRUCTURED","BALANCED","SPACIOUS"] as const).map((item)=><button type="button" className={planningStyle===item?"active":""} onClick={()=>setPlanningStyle(item)} key={item}>{item.charAt(0)+item.slice(1).toLowerCase()}</button>)}</div><div className="tag-cloud">{["Family","Meditation","Learning","Hobby","Reading","Walk","Rest","Nothing at all"].map((item)=><button type="button" className={freeUses.includes(item)?"active":""} onClick={()=>toggle(freeUses,item,setFreeUses)} key={item}>{item}</button>)}</div></div>,
    <div className="onboard-question wide" key="water"><Waves className="question-icon"/><span className="overline">HYDRATION</span><h1>What’s your daily water target?</h1><div className="water-presets">{[2000,2500,3000,3500].map((amount)=><button type="button" className={water===amount?"active":""} onClick={()=>setWater(amount)} key={amount}>{amount/1000} L</button>)}</div></div>,
    <div className="onboard-question wide" key="improve"><Heart className="question-icon"/><span className="overline">YOUR INTENTION</span><h1>What would you like DayOS to improve?</h1><div className="tag-cloud">{improvements.map((item)=><button type="button" className={goals.includes(item)?"active":""} onClick={()=>toggle(goals,item,setGoals)} key={item}>{item}</button>)}</div></div>,
    <div className="onboard-question ready" key="ready"><div className="ready-mark"><span>✓</span></div><span className="overline">READY TO PERSONALIZE</span><h1>Build a day around you.</h1><p>Your answers will be saved to your account and used to generate your first plan, habits, and future recommendations.</p>{error&&<p className="form-error" role="alert">{error}</p>}<Button size="lg" disabled={saving} onClick={()=>void finish()}>{saving?"Building your day…":"Build my first day"} <ArrowRight size={17}/></Button></div>
  ];
  const last=steps.length-1; const canContinue = (step !== 2 || selected.length > 0) && (step !== 4 || routines.filter((item)=>item.active).every((item)=>item.days.length>0)) && (step !== 7 || freeUses.length>0);
  return <main className="onboarding ambient-page"><header><Link className="brand" href="/"><span className="brand-mark">D</span><span>DayOS</span></Link><span>{Math.min(step+1,last)} of {last}</span></header><div className="progress"><i style={{width:`${Math.min((step+1)/last*100,100)}%`}}/></div><AnimatePresence mode="wait"><motion.section key={step} initial={{opacity:0,y:28,scale:.975,filter:"blur(14px)"}} animate={{opacity:1,y:0,scale:1,filter:"blur(0px)"}} exit={{opacity:0,y:-18,scale:1.015,filter:"blur(10px)"}} transition={{type:"spring",stiffness:230,damping:26,mass:.8}}>{steps[step]}</motion.section></AnimatePresence>{step<last&&<footer><Button variant="ghost" disabled={step===0} onClick={()=>setStep((value)=>value-1)}><ArrowLeft size={16}/> Back</Button><Button disabled={!canContinue} onClick={()=>setStep((value)=>value+1)}>Continue <ArrowRight size={16}/></Button></footer>}</main>;
}
