"use client";
import { AnimatePresence, motion } from "motion/react";
import { ArrowLeft, ArrowRight, BookOpen, BriefcaseBusiness, Dumbbell, Heart, Moon, PersonStanding, Sun, Users, Waves } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";

const spaces = [{label:"Work",icon:BriefcaseBusiness},{label:"Learning",icon:BookOpen},{label:"Exercise",icon:Dumbbell},{label:"Reading",icon:BookOpen},{label:"Personal projects",icon:PersonStanding},{label:"Family",icon:Users},{label:"Recovery",icon:Waves}];
const improvements = ["Focus","Consistency","Learning","Health","Balance","Less wasted time","Better routines"];
export function OnboardingFlow() {
  const router = useRouter(); const [step, setStep] = useState(0); const [wake, setWake] = useState("07:00"); const [sleep, setSleep] = useState("23:00"); const [selected, setSelected] = useState(["Work","Learning","Exercise","Recovery"]); const [exercise, setExercise] = useState("Evening"); const [water, setWater] = useState(3000); const [goals, setGoals] = useState(["Focus","Balance"]);
  const toggle = (list: string[], value: string, update: (next:string[])=>void) => update(list.includes(value) ? list.filter((item)=>item!==value) : [...list,value]);
  const steps = [
    <div className="onboard-question" key="wake"><Sun className="question-icon"/><span className="overline">BEGIN YOUR DAY</span><h1>When do you normally wake up?</h1><p>This sets the earliest edge of your schedule.</p><input className="time-input" type="time" value={wake} onChange={(event)=>setWake(event.target.value)}/></div>,
    <div className="onboard-question" key="sleep"><Moon className="question-icon"/><span className="overline">PROTECT RECOVERY</span><h1>When would you like to sleep?</h1><p>DayOS never schedules beyond this boundary.</p><input className="time-input" type="time" value={sleep} onChange={(event)=>setSleep(event.target.value)}/></div>,
    <div className="onboard-question wide" key="space"><span className="overline">YOUR PRIORITIES</span><h1>What deserves space in your day?</h1><p>Choose everything you want the plan to protect.</p><div className="choice-grid">{spaces.map(({label,icon:Icon})=><button key={label} className={selected.includes(label)?"choice active":"choice"} onClick={()=>toggle(selected,label,setSelected)}><Icon/>{label}</button>)}</div></div>,
    <div className="onboard-question" key="work"><BriefcaseBusiness className="question-icon"/><span className="overline">YOUR COMMITMENTS</span><h1>What are your usual work hours?</h1><div className="time-range"><input type="time" defaultValue="09:00"/><ArrowRight/><input type="time" defaultValue="18:00"/></div><label className="check-row"><input type="checkbox"/> My work hours vary</label></div>,
    <div className="onboard-question wide" key="exercise"><Dumbbell className="question-icon"/><span className="overline">MOVE WELL</span><h1>When does exercise feel best?</h1><div className="segmented big">{["Morning","Afternoon","Evening","No preference"].map((item)=><button className={exercise===item?"active":""} onClick={()=>setExercise(item)} key={item}>{item}</button>)}</div></div>,
    <div className="onboard-question wide" key="meals"><span className="overline">MEAL WINDOWS</span><h1>Keep time open to refuel.</h1><p>These are flexible windows, not rigid alarms.</p><div className="meal-list">{[["Breakfast","08:00","09:00"],["Lunch","13:00","14:30"],["Dinner","19:00","20:30"]].map(([name,start,end])=><div key={name}><b>{name}</b><input type="time" defaultValue={start}/><span>to</span><input type="time" defaultValue={end}/></div>)}</div></div>,
    <div className="onboard-question wide" key="water"><Waves className="question-icon"/><span className="overline">HYDRATION</span><h1>What’s your daily water target?</h1><div className="water-presets">{[2000,2500,3000,3500].map((amount)=><button className={water===amount?"active":""} onClick={()=>setWater(amount)} key={amount}>{amount/1000} L</button>)}</div></div>,
    <div className="onboard-question wide" key="improve"><Heart className="question-icon"/><span className="overline">YOUR INTENTION</span><h1>What would you like DayOS to improve?</h1><div className="tag-cloud">{improvements.map((item)=><button className={goals.includes(item)?"active":""} onClick={()=>toggle(goals,item,setGoals)} key={item}>{item}</button>)}</div></div>,
    <div className="onboard-question ready" key="ready"><div className="ready-mark"><span>✓</span></div><span className="overline">ALL SET</span><h1>Your day is ready.</h1><p>We’ll keep the important things visible and leave breathing room where it belongs.</p><Button size="lg" onClick={()=>router.push("/app/today")}>Build my first day <ArrowRight size={17}/></Button></div>
  ];
  return <main className="onboarding ambient-page"><header><Link className="brand" href="/"><span className="brand-mark">D</span><span>DayOS</span></Link><span>{Math.min(step+1,8)} of 8</span></header><div className="progress"><i style={{width:`${Math.min((step+1)/8*100,100)}%`}}/></div><AnimatePresence mode="wait"><motion.section key={step} initial={{opacity:0,y:28,scale:.975,filter:"blur(14px)"}} animate={{opacity:1,y:0,scale:1,filter:"blur(0px)"}} exit={{opacity:0,y:-18,scale:1.015,filter:"blur(10px)"}} transition={{type:"spring",stiffness:230,damping:26,mass:.8}}>{steps[step]}</motion.section></AnimatePresence>{step<8&&<footer><Button variant="ghost" disabled={step===0} onClick={()=>setStep((value)=>value-1)}><ArrowLeft size={16}/> Back</Button><Button onClick={()=>setStep((value)=>value+1)}>Continue <ArrowRight size={16}/></Button></footer>}</main>;
}
