"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { AnimatePresence, motion } from "motion/react";
import { BarChart3, CalendarDays, CheckSquare2, CircleUserRound, Command, Droplets, Flame, Menu, Moon, Plus, Search, Settings, Sun, Target, X } from "lucide-react";
import { useTheme } from "next-themes";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { useDayOS } from "@/components/providers";
import { Button } from "@/components/ui/button";

const primary = [{href:"/app/today",label:"Today",icon:Target},{href:"/app/tasks",label:"Tasks",icon:CheckSquare2},{href:"/app/habits",label:"Habits",icon:Flame},{href:"/app/calendar",label:"Calendar",icon:CalendarDays},{href:"/app/insights",label:"Insights",icon:BarChart3}] as const;
export function AppShell({ children }: { children: ReactNode }) {
  const path = usePathname(); const { resolvedTheme, setTheme } = useTheme(); const [quick, setQuick] = useState(false); const [mobile, setMobile] = useState(false);
  return <div className="app-frame ambient-page">
    <aside className={mobile?"sidebar mobile-open":"sidebar"}><div className="sidebar-top"><Link href="/app/today" className="brand"><span className="brand-mark">D</span><span>DayOS</span></Link><button className="mobile-close" onClick={()=>setMobile(false)} aria-label="Close menu"><X/></button></div><nav>{primary.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setMobile(false)} className={path===href?"active":""}><Icon/><span>{label}</span>{path===href&&<motion.i layoutId="nav-active" transition={{type:"spring",stiffness:360,damping:32,mass:.72}}/>}</Link>)}</nav><div className="sidebar-bottom"><Link href="/app/settings" className={path==="/app/settings"?"active":""}><Settings/><span>Settings</span></Link><div className="profile"><div className="avatar">AK</div><div><b>Alex Kapoor</b><small>Personal space</small></div><CircleUserRound/></div></div></aside>
    <AnimatePresence>{mobile&&<motion.button className="sidebar-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.22}} onClick={()=>setMobile(false)} aria-label="Close navigation"/>}</AnimatePresence>
    <div className="app-body"><header className="mobile-header"><button onClick={()=>setMobile(true)} aria-label="Open menu"><Menu/></button><Link href="/app/today" className="brand"><span className="brand-mark">D</span><span>DayOS</span></Link><button onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")} aria-label="Toggle theme"><Sun className="theme-sun"/><Moon className="theme-moon"/></button></header><div className="top-toolbar"><button className="search"><Search/> <span>Find anything</span><kbd><Command/> K</kbd></button><button onClick={()=>setTheme(resolvedTheme==="dark"?"light":"dark")} aria-label="Toggle light and dark mode"><Sun className="theme-sun"/><Moon className="theme-moon"/></button><Button size="sm" onClick={()=>setQuick(true)}><Plus size={15}/> Quick add</Button></div><AnimatePresence mode="wait" initial={false}><motion.div className="route-transition" key={path} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28,ease:[.2,.8,.2,1]}}>{children}</motion.div></AnimatePresence></div>
    <nav className="bottom-nav">{primary.filter((_,index)=>index!==3).map(({href,label,icon:Icon},index)=><span key={href}>{index===2&&<button className="bottom-add" onClick={()=>setQuick(true)} aria-label="Quick add"><Plus/></button>}<Link href={href} className={path===href?"active":""}><Icon/><small>{label}</small></Link></span>)}</nav>
    <QuickAdd open={quick} onOpenChange={setQuick}/>
  </div>;
}

function QuickAdd({ open, onOpenChange }: { open: boolean; onOpenChange(value:boolean):void }) {
  const { addTask, logWater } = useDayOS(); const [type,setType]=useState("Task"); const { register, handleSubmit, reset } = useForm<{title:string;duration:number;priority:"LOW"|"MEDIUM"|"HIGH"}>({defaultValues:{title:"",duration:30,priority:"MEDIUM"}});
  const save = handleSubmit(async (value)=>{ if(type==="Water") await logWater(250); else await addTask({title:value.title,estimatedMinutes:Number(value.duration),priority:value.priority}); reset(); onOpenChange(false); });
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><AnimatePresence>{open&&<Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div className="dialog-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.24}}/></Dialog.Overlay><Dialog.Content asChild><motion.div className="dialog glass glass-depth-4" initial={{opacity:0,scale:.9,y:28,filter:"blur(14px)"}} animate={{opacity:1,scale:1,y:0,filter:"blur(0px)"}} exit={{opacity:0,scale:.94,y:18,filter:"blur(9px)"}} transition={{type:"spring",stiffness:300,damping:27,mass:.78}}><Dialog.Title>Quick add</Dialog.Title><Dialog.Description>Make space for something new.</Dialog.Description><Dialog.Close className="dialog-close"><X/></Dialog.Close><div className="quick-types">{[{n:"Task",i:CheckSquare2},{n:"Event",i:CalendarDays},{n:"Habit",i:Flame},{n:"Water",i:Droplets}].map(({n,i:Icon})=><button className={type===n?"active":""} onClick={()=>setType(n)} key={n}><Icon/>{n}</button>)}</div>{type==="Water"?<div className="quick-water"><Droplets/><h3>Log a glass of water?</h3><p>250 ml will be added to today.</p><Button onClick={()=>void save()}>Add 250 ml</Button></div>:<form onSubmit={save}><label>What is it?<input autoFocus {...register("title",{required:true})} placeholder={type==="Task"?"Finish project outline":`New ${type.toLowerCase()}`}/></label><div className="form-row"><label>Duration<select {...register("duration",{valueAsNumber:true})}><option value="15">15 min</option><option value="30">30 min</option><option value="45">45 min</option><option value="60">1 hour</option><option value="90">90 min</option></select></label><label>Priority<select {...register("priority")}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label></div><Button type="submit" className="full">Add {type.toLowerCase()}</Button></form>}</motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root>;
}
