"use client";
import { motion } from "motion/react";
import { ArrowUpDown, CalendarPlus, Check, CheckCircle2, ChevronDown, Circle, Clock3, Filter, MoreHorizontal, Plus, Search, Sparkles, Zap } from "lucide-react";
import { useMemo, useState } from "react";
import { useDayOS } from "@/components/providers";
import { GlassCard, GlassPill } from "@/components/glass/glass";
import { Button } from "@/components/ui/button";

const tabs=["Today","Upcoming","Backlog","Completed"];
export function TasksView(){const {tasks,completeTask,addTask}=useDayOS();const [tab,setTab]=useState("Today");const [search,setSearch]=useState("");const [adding,setAdding]=useState(false);const filtered=useMemo(()=>tasks.filter((item)=>item.title.toLowerCase().includes(search.toLowerCase())&&(tab!=="Completed"||item.status==="COMPLETED")&&(tab!=="Backlog"||item.status==="BACKLOG")),[tasks,search,tab]);
return <main className="workspace list-workspace"><header className="page-heading compact"><div><span className="overline">YOUR COMMITMENTS</span><h1>Tasks</h1><p>Make time for the work that matters.</p></div><Button onClick={()=>setAdding(true)}><Plus/> New task</Button></header><div className="list-toolbar"><div className="tabs">{tabs.map((item)=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}<span>{item==="Completed"?tasks.filter((task)=>task.status==="COMPLETED").length:item==="Backlog"?tasks.filter((task)=>task.status==="BACKLOG").length:""}</span></button>)}</div><div className="list-tools"><label><Search/><input placeholder="Search tasks" value={search} onChange={(event)=>setSearch(event.target.value)}/></label><button><Filter/> Filter</button><button><ArrowUpDown/> Sort</button></div></div>
<section className="task-list"><div className="task-summary"><div><span className="summary-icon"><Sparkles/></span><div><b>{filtered.filter((item)=>item.status!=="COMPLETED").length} activities</b><p>{Math.round(filtered.reduce((sum,item)=>sum+item.estimatedMinutes,0)/60*10)/10} hours of intention</p></div></div><GlassPill>Balanced load</GlassPill></div>{filtered.map((task,index)=><motion.article layout initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.03}} key={task.id}><button className={task.status==="COMPLETED"?"task-check done":"task-check"} onClick={()=>void completeTask(task.id)}>{task.status==="COMPLETED"?<Check/>:<Circle/>}</button><div className="task-main"><h3>{task.title}</h3><div><span className={`area-dot ${task.lifeArea.toLowerCase()}`}/>{task.lifeArea.charAt(0)+task.lifeArea.slice(1).toLowerCase()}<span>·</span><Clock3/>{task.estimatedMinutes} min<span>·</span><Zap/>{task.energyRequired.replace("_"," ").toLowerCase()}</div></div><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><Button variant="ghost" size="sm"><CalendarPlus/> Schedule</Button><button className="more"><MoreHorizontal/></button></motion.article>)}{!filtered.length&&<GlassCard className="empty-state"><CheckCircle2/><h2>Your backlog is clear.</h2><p>Add something worth making time for.</p><Button onClick={()=>setAdding(true)}><Plus/> Add a task</Button></GlassCard>}</section>
{adding&&<div className="inline-composer glass glass-depth-3"><div><span className="overline">NEW TASK</span><h2>What deserves time?</h2></div><input autoFocus placeholder="Name this task" onKeyDown={(event)=>{if(event.key==="Enter"&&event.currentTarget.value){void addTask({title:event.currentTarget.value,estimatedMinutes:30,priority:"MEDIUM"});setAdding(false)}}}/><div className="form-row"><button><Clock3/>30 min<ChevronDown/></button><button><Zap/>Medium energy<ChevronDown/></button><button>Medium priority<ChevronDown/></button></div><div><Button variant="ghost" onClick={()=>setAdding(false)}>Cancel</Button><Button onClick={()=>setAdding(false)}>Add task</Button></div></div>}</main>}
